### ISSUE TITLE
Implement permissions system

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#17]
Server roles should have specific permitions set. These should be set in a permissions.xml file located inside the config file

**Comment by EthanTheMaster** [comment]
Could you elaborate on what you mean and what are you are looking for? Maybe an example scenario?

**Comment by Pedro12909** [comment]
Hello. At the moment, RexCord accepts commands from everyone in the server. This is not intended as the user may want to assign different commands to different roles. To fix this, there should be a permissions.xml file inside the config folder.
This file should look something like this:

```xml
<rexcord>
    <group id="music_master">
        <isDefault>false</isDefault>
        <users>
            <user>123123123123</user> <!-- user ID -->
        </users>
        
        <permissions>
            <command>*</command> <!-- '*' gives access to all commands -->
        </permissions>
    </group>
    
    <group id="moderator">
        <isDefault>false</isDefault>
        <users>
            <user>233948930200</user>
            <user>543875849355</user>
            <user>949447893098</user>
        </users>
        
        <permissions>
            <command>gif</command>
            <command>play</command>
            <command>skip</command>
        </permissions>
    </group>
    
    <group id="default">
        <isDefault>true</isDefault>
        <permissions>
            <command>greet</command>
            <command>summon</command>
            <command>joke</command>
        </permissions>
    </group>
</rexcord>
```

If you want to take on this issue, feel free to do it as whatever you wish. Also, there's no need to overthink it for now. As long as it is a functional permissions system, it is good enough for us. :)
