### ISSUE TITLE
Make configuration file a XML document

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#20]
Configuration file should be a XML document for better readibility and easier manipulation.
However the ConfigReader class should also read that file and properly set the values inside it. As it is, it won't read XML since it's designed to read from our cfg file.

**Comment by tminussi** [comment]
Pedro, I have added this feature and corrected all the build problems. Everything looks good now.

Thanks and hope you approve it.

Thales.

**Comment by Pedro12909** [comment]
Hi @tminussi . I'm sorry I didn't explain this issue correctly. You xml example looks good, however the ConfigReader class should also read that file and properly set the values inside it. As it is, it won't read XML since it's designed to read from our cfg file. If you're still interested, open another PR referencing this same issue! Thanks for contributing!
