### ISSUE TITLE
Add RemindMe Command

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#31]
RemindMe command is a well known and useful feature already present in some Reddit bots.
The user posts something like:
`//remindme 27/05/2017 21:00:00 <custom_message> ` and RexCord sends a PM to that user when it reached the specified date

Other command formats can be found [here](https://www.reddit.com/r/RemindMeBot/comments/2862bd/remindmebot_date_options/)

**Comment by freitzzz** [comment]
Very good idea! Looking forward for this one.
