### ISSUE TITLE
Joke command not working properly

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#33]

**Comment by savagplatypus** [comment]
I would be down to work on this. What is the joke command that is not working properly.

**Comment by Nightfirecat** [comment]
I assume [JokeCommand.java](https://github.com/Pedro12909/RexCord/blob/master/src/main/java/commands/JokeCommand.java). What's not working properly about it, I'm not sure--perhaps it just isn't working?

**Comment by Pedro12909** [comment]
Hi. From what I've seen, there's an IO exception being thrown somewhere, that's why RexCord returns `Could not find a sub` when `joke` command is used.

**Comment by freitzzz** [comment]
Joke command now works properly. Much thanks to @EthanTheMaster for his contribution, and explanation about why it was not working!
