### ISSUE TITLE
Format Bot Messages

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#40]
As it is, RexCord messages seem pretty boring and ugly. Discord4J has a way of sending much more elegant messages by using embedded content. Take a look [here](http://discord4j.readthedocs.io/en/latest/Making-embedded-content-using-EmbedBuilder/) to see what I'm talking about:

So, instead of sending messages in code blocks, it should send text as embedded content

**Comment by jmerle** [comment]
I'll work on it, sounds like an interesting feature.
