### ISSUE TITLE
src\main\java\utils\XmlParser.java:0: error: File does not end with a newline.

### ISSUE THREAD

**Issue by beatyt** [Pedro12909/RexCord#45]
By default Checkstyle uses system line endings. Windows uses CRLF but all of these files were created with LF endings.

The fix is to change
```xml
    <module name="NewlineAtEndOfFile" />
```

to

```xml
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf"/>
    </module>
```

**Comment by dodie** [comment]
Hi! I've submitted a PR for this, could you review it, please?
