### ISSUE TITLE
Add Unit Tests for commands package

### ISSUE THREAD

**Issue by Pedro12909** [Pedro12909/RexCord#56]
All classes inside the commands package should be properly tested.

**Comment by GaruGaru** [comment]
I'd like to word on this, i gave a quick look at the source code and it should be doable by mocking the RexCord class in order to make assertions on the command output

**Comment by Pedro12909** [comment]
@GaruGaru Consider this issue assigned to you! Feel free to come to come to our discord channel if you need any help!
